feat: allow signing function only for bundled txs
warp-contracts/warp pull request #241
Opened 2022-10-19 15:18 UTC by asiaziola

2022-10-20 16:55 UTC, asiaziola commented on src/contract/HandlerBasedContract.ts
> +        this.signer = { function: signer, type: 'custom' };
done

2022-10-21 10:56 UTC, ppedziwiatr requested changes

2022-10-21 10:56 UTC, ppedziwiatr commented on src/contract/Contract.ts
> +  connect(signature: Signature): Contract<State>;
tu źle.

Miało być:
`signer: ArWallet | Signature`

gdzie `Signature` to
```
export interface Signature {
  signer: SigningFunction;
  signatureType: 'arweave' | 'ethereum';
}
```

2022-10-21 11:04 UTC, ppedziwiatr commented on src/contract/Contract.ts
> +  connect(signature: Signature): Contract<State>;
... w przypadku przekazania jako `ArWallet`, poza generowaniem funkcji podpisującej, ustawiamy też automatycznie `signatureType` na `arweave`.

2022-10-21 14:08 UTC, ppedziwiatr requested changes

2022-10-21 14:19 UTC, asiaziola commented on src/contract/HandlerBasedContract.ts
> +    if ((signature as Signature).signer) {
done

2022-10-21 14:19 UTC, asiaziola commented on src/contract/HandlerBasedContract.ts
> +    if (this.signature.signatureType !== 'arweave' && (!bundleInteraction || !(this.warp.environment === 'mainnet'))) {
done

2022-10-24 08:02 UTC, ppedziwiatr commented on src/contract/HandlerBasedContract.ts
> +    if (!this.signature.signer) {
`.signer` out

2022-10-24 08:08 UTC, ppedziwiatr commented on src/contract/HandlerBasedContract.ts
> +    if (!this.signature.signer) {
remove `.signer`

2022-10-24 08:10 UTC, ppedziwiatr commented on src/contract/HandlerBasedContract.ts
> +    } else if (this.signature.signer) {
remove `.signer`

2022-10-24 08:11 UTC, ppedziwiatr commented on src/contract/HandlerBasedContract.ts
> +    if (!this.signature.signer) {
remove `.signer`

2022-10-24 08:13 UTC, ppedziwiatr commented on src/contract/HandlerBasedContract.ts
> +      this.signature.signer,
`this.signature?.signer`

2022-10-25 12:07 UTC, merged