feat: register contract
warp-contracts/warp pull request #299
Opened 2022-12-20 15:57 UTC by asiaziola

2022-12-27 14:54 UTC, ppedziwiatr requested changes

2022-12-27 14:54 UTC, ppedziwiatr commented on src/contract/deploy/impl/DefaultCreateContract.ts
> +      body: JSON.stringify({ id })
add bundlr node as parameter

2022-12-28 15:18 UTC, asiaziola commented on README.md
> +#### deployBundled
:<

2022-12-28 15:18 UTC, asiaziola commented on src/contract/deploy/impl/DefaultCreateContract.ts
> +      body: JSON.stringify({ id })
done

2022-12-28 15:56 UTC, ppedziwiatr approved these changes

2022-12-28 16:47 UTC, merged