Twl/the one with kv storage query ranges internal writes kv del
warp-contracts/warp pull request #383
Opened 2023-03-30 08:14 UTC by Tadeuchi

2023-04-11 12:22 UTC, ppedziwiatr requested changes

2023-04-11 12:22 UTC, ppedziwiatr commented on src/contract/states/ContractInteractionState.ts
> +      return await this.rollbackKVs();
add `this.reset()` here?

2023-04-14 10:01 UTC, Tadeuchi commented on src/cache/impl/LevelDbCache.ts
> +      // <separator><contract_tx_id (43 chars)><separator><sort_key>
changed to `const sortKey = joinedKey.split(this.subLevelSeparator)[1];`

2023-04-14 10:01 UTC, Tadeuchi commented on src/cache/SortKeyCacheRangeOptions.ts
> +  gte?: string;
yes, correct

2023-04-14 10:02 UTC, Tadeuchi commented on src/contract/states/ContractInteractionState.ts
> +      return await this.rollbackKVs();
as you wish

2023-04-14 10:04 UTC, Tadeuchi commented on src/cache/impl/LevelDbCache.ts
> +    if (this._rollbackBatch && this._rollbackBatch.length > 0) {
added some simple checking that the previous transaction has finished
there is some marker saved on kv.begin 
and deleted on commit or rollback
on open the kvStorage should throw an error if transaction marker found

it seems that the tx id is not needed for this

2023-04-14 10:55 UTC, ppedziwiatr approved these changes

2023-04-14 12:37 UTC, merged